### ISSUE TITLE
Support io.js

### ISSUE THREAD

**Issue by mpreziuso** [node-xmpp/node-expat#106]
Many packages require `node-expat` and, as you know, node.js has been stuck at v0.10 for almost 2 years now.
[io.js](https://github.com/iojs/io.js) is trying to save the `node.js` community and today released the v1.0.0. 

As `npm install node-expat` under `io.js` outputs:

    > node-expat@2.3.4 install /path/to/node_modules/node-expat
    > node-gyp rebuild

    gyp WARN install got an error, rolling back install
    gyp ERR! configure error 
    gyp ERR! stack Error: 404 status code downloading tarball
    gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
    gyp ERR! stack     at Request.emit (events.js:117:20)
    gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1255:10)
    gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:399:21)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:89:23)
    gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:290:20)
    gyp ERR! stack     at TLSSocket.emit (events.js:95:17)
    gyp ERR! stack     at readableAddChunk (_stream_readable.js:143:16)
    gyp ERR! stack     at TLSSocket.Readable.push (_stream_readable.js:106:10)
    gyp ERR! System Linux 3.10.0-123.13.2.el7.x86_64

are you planning to do a node-expat release for io.js (maybe io-expat :) )?

**Comment by astro** [comment]
404? Is there a different npmjs.org for io.js?

**Comment by chris-rock** [comment]
I would prefer to make the same release working with nodejs and io.js. To maintain two versions would make the life difficult for users and maintainers.

**Comment by corbinu** [comment]
That was a gyp error which was fixed in io.js 1.0.1

The issue now is that node-expat is incompatible with the latest version of v8

```
  CXX(target) Release/obj.target/node_expat/node-expat.o
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:504:19: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
      v8::String::ExternalAsciiStringResource *resource) {
      ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                  ExternalStringResource
/Users/corbinu/.node-gyp/1.0.1/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:503:36: error: redefinition of 'NanNew'
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:498:36: note: previous definition is here
  NAN_INLINE v8::Local<v8::String> NanNew(
                                   ^
../node_modules/nan/nan.h:2184:12: error: no member named 'IsExternalAscii' in 'v8::String'; did you mean 'IsExternal'?
  if (str->IsExternalAscii()) {
           ^~~~~~~~~~~~~~~
           IsExternal
/Users/corbinu/.node-gyp/1.0.1/deps/v8/include/v8.h:1980:8: note: 'IsExternal' declared here
  bool IsExternal() const;
       ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:2185:23: error: no type named 'ExternalAsciiStringResource' in 'v8::String'; did you mean 'ExternalStringResource'?
    const v8::String::ExternalAsciiStringResource* ext;
          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
                      ExternalStringResource
/Users/corbinu/.node-gyp/1.0.1/deps/v8/include/v8.h:2016:19: note: 'ExternalStringResource' declared here
  class V8_EXPORT ExternalStringResource
                  ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:2186:16: error: no member named 'GetExternalAsciiStringResource' in 'v8::String'; did you mean
      'GetExternalOneByteStringResource'?
    ext = str->GetExternalAsciiStringResource();
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               GetExternalOneByteStringResource
/Users/corbinu/.node-gyp/1.0.1/deps/v8/include/v8.h:2083:40: note: 'GetExternalOneByteStringResource' declared here
  const ExternalOneByteStringResource* GetExternalOneByteStringResource() const;
                                       ^
In file included from ../node-expat.cc:1:
../node_modules/nan/nan.h:2186:9: error: assigning to 'const v8::String::ExternalStringResource *' from incompatible type 'const
      v8::String::ExternalOneByteStringResource *'
    ext = str->GetExternalAsciiStringResource();
        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:2187:11: error: assigning to 'const char *' from incompatible type 'const uint16_t *' (aka 'const unsigned short *')
    *data = ext->data();
          ^ ~~~~~~~~~~~
../node-expat.cc:42:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2354:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:150:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2354:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
../node-expat.cc:223:9: warning: 'NanRawString' is deprecated [-Wdeprecated-declarations]
        NanRawString(args[0], Nan::ASCII, NULL, encoding, 32, 0);
        ^
../node_modules/nan/nan.h:2354:33: note: 'NanRawString' has been explicitly marked deprecated here
NAN_DEPRECATED NAN_INLINE void* NanRawString(
                                ^
3 warnings and 7 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
```

**Comment by jcrugzz** [comment]
Updating to the latest version of [`nan`](https://github.com/rvagg/nan) (1.5) should resolve this.

**Comment by lloydwatkin** [comment]
I assumed a `nan` update would solve things. Let me get io.js installed and see if I can get things going :)

**Comment by mpreziuso** [comment]
:+1 That's great news :)

**Comment by lloydwatkin** [comment]
Ok its not a simple case of updating `nan` unfortunately. I'm awaiting an update of `iconv` first, https://github.com/bnoordhuis/node-iconv/issues/106
.

**Comment by lloydwatkin** [comment]
https://github.com/iojs/io.js/issues/456

**Comment by corbinu** [comment]
Now that iconv is updated what is blocking this? Anything I can do to help?

**Comment by lloydwatkin** [comment]
@corbinu  I think there may be some changes still due to nan upgrades but I'm not 100%. If you have time before me I'd very happily accept a pull request :)

**Comment by lloydwatkin** [comment]
Fixed thanks to @corbinu !

**Comment by astro** [comment]
Very nice!
