### ISSUE TITLE
node-expat installing without build directory with bindings file

### ISSUE THREAD

**Issue by NataliaLKB** [node-xmpp/node-expat#108]
Error thrown repeatedly on Travis builds. Build system information:

Travis CI virtual machines are based on Ubuntu 12.04 LTS Server Edition 64 bit

- node version 0.10.35
- npm version 1.4.28
- nvm version 0.20.0

Before installation scripts: 

- sudo apt-get update
- sudo apt-get install libexpat1-dev

Error is: 

```
/home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/build/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/build/Debug/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/build/Release/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/out/Debug/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/Debug/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/out/Release/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/Release/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/build/default/node_expat.node
 → /home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/compiled/0.10.32/linux/x64/node_expat.node
    at bindings (/home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/travis/build/foundersandcoders/camdenmaps/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/travis/build/foundersandcoders/camdenmaps/server/lib/xml-parser.js:3:9)
    at Module._compile (module.js:456:26)
```

No error is thrown on the installation, but when the module is required. On travis it throws the error right after SauceLabs starts its selenium server for our tests. 

Is there something I am missing?

**Comment by lloydwatkin** [comment]
Hmm strange, I've just run master against v0.10.35 and all seems good here: https://travis-ci.org/node-xmpp/node-expat/jobs/44514960

Are things running ok for you locally?

**Comment by NataliaLKB** [comment]
Hey thanks for the quick reply @lloydwatkin.

Locally everything runs perfectly fine, one of the reasons I am stumped. Mind you, I am still quite the beginner. 

I managed to get a few passing builds by using gulp to reinstall node-expat right before tests start: https://travis-ci.org/foundersandcoders/camdenmaps (Look at line 692). It seems to be rebuilding node-gyp.

I noticed that before installation your build had the lines:

```
sudo rm -rf /dev/shm
sudo ln -s /run/shm /dev/shm
```
Would this maybe be what I am missing?

**Comment by lloydwatkin** [comment]
Possibly, its related to permissions (unfortunately the description no longer exists https://github.com/travis-ci/travis-cookbooks/issues/155), it be worth a go at least :)

**Comment by NataliaLKB** [comment]
@lloydwatkin So sorry for the late reply. Busy week. Thank you so much for all your help. I do think this is an issue with node-gyp, not this module so I am going to close this issue. Thanks again!

**Comment by lloydwatkin** [comment]
No problem :)
