### ISSUE TITLE
Parser is not running `startElement` if XML contains `&ndash`

### ISSUE THREAD

**Issue by voronianski** [node-xmpp/node-expat#111]
This looks strange however I'm not an expert in XML formatting..

I have a XML response which replaced all `#8122;` (which is dash symbol) with `&ndash`. Unfortunately `startElement` of node-expat's parser even doesn't run now.

**Comment by astro** [comment]
Trying to reproduce with `<lol>&#8211;&ndash;</lol>` and getting:
`[["startElement","lol",{}],["text","–"],["error","undefined entity"]]`

Please paste your sample XML.

**Comment by lloydwatkin** [comment]
Closing as there's been no response from the original poster.
