### ISSUE TITLE
cannot install on Windows 8.1 64bit with MSVS version 2013

### ISSUE THREAD

**Issue by hellerim** [node-xmpp/node-expat#113]
After my first try which failed I found the hint on this forum to use the msvs_version switch which looked promising to me. However, this failed again, but differently. It looks as if it has to do with the fact that the machine environment is 64 bits with Win 8.1 64 bit. Here is the command line output produced:

C:\Users\heller.HELLERIM>npm install -g xml-stream --msvs_version=2013
|

> node-expat@2.3.7 install C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat
> node-gyp rebuild

/
C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..
\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  xmlparse.c
  xmltok.c
  xmlrole.c
..\..\..\deps\libexpat\lib\xmlparse.c(1844): warning C4244: 'return' : conversion from '__int64' to 'XML_Index', possible loss of data [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\build\deps\libexpat\expat.vcxproj]
  expat.vcxproj -> C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\build\Release\\libexpat.lib
  node-expat.cc
..\node-expat.cc(42): warning C4996: 'NanRawString': was declared deprecated [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\build\node_expat.vcxproj]
          C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\node_modules\nan\nan.h(2110) : see declaration of 'NanRawString'
..\node-expat.cc(137): warning C4267: 'argument' : conversion from 'size_t' to 'int', possible loss of data [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\build\node_expat.vcxproj]
..\node-expat.cc(150): warning C4996: 'NanRawString': was declared deprecated [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_module
s\node-expat\build\node_expat.vcxproj]
          C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\node_modules\nan\nan.h(2110) : see declaration of 'NanRawString'
..\node-expat.cc(223): warning C4996: 'NanRawString': was declared deprecated [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_module
s\node-expat\build\node_expat.vcxproj]
          C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\node_modules\nan\nan.h(2110) : see declaration of 'NanRawString'
C:\Users\heller.HELLERIM\.node-gyp\0.10.29\deps\v8\include\v8.h(179): warning C4506: no definition for inline function 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\build\node_expat.vcx
proj]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat\build\node_expat.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\node-expat
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok

> iconv@2.1.6 install C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\iconv
> node-gyp rebuild

/
C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\iconv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  iconv.c
  libiconv.vcxproj -> C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\iconv\build\Release\\libiconv.lib
  binding.cc
C:\Users\heller.HELLERIM\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\iconv\build\iconv.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\iconv\build\iconv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\xml-stream\node_modules\iconv
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! node-expat@2.3.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.7 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "xml-stream" "--msvs_version=2013"
npm ERR! cwd C:\Users\heller.HELLERIM
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\heller.HELLERIM\npm-debug.log
npm ERR! not ok code 0

Any idea what could help?

**Comment by lloydwatkin** [comment]
Could you try installing the latest version of `node-expat` using the same command line switches as you have in your example and see if that helps?

**Comment by hellerim** [comment]
Similar result:


C:\Users\heller.HELLERIM>npm install -g node-expat --msvs_version=2013
/


> iconv@2.1.6 install C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv
> node-gyp rebuild


C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  iconv.c
  libiconv.vcxproj -> C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv\build\Release\\libiconv.lib
  binding.cc
C:\Users\heller.HELLERIM\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv\build\iconv.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv\build\iconv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
ERR! cwd C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! iconv@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.6 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-expat" "--msvs_version=2013"
npm ERR! cwd C:\Users\heller.HELLERIM
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\heller.HELLERIM\npm-debug.log
npm ERR! not ok code 0

**Comment by lloydwatkin** [comment]
Similar but different, now node-expat is all good, `iconv` the issue. We're using the latest version 2.1.6. I'd suggest wiping your ~/.node-gyp directory and trying again, then if not I'd raise an issue with that project - https://github.com/bnoordhuis/node-iconv

Ultimately when this issue is sorted we'll need to talk to the `xml-stream` project to get them to upgrade `node-expat`.

**Comment by hellerim** [comment]
Thank you very much! Unfortunately, it still doesn't work after wiping ~\.node-gyp:

C:\Users\heller.HELLERIM>npm install -g node-expat --msvs_version=2013
\


> iconv@2.1.6 install C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv
> node-gyp rebuild


C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  iconv.c
  libiconv.vcxproj -> C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv\build\Release\\libiconv.lib
  binding.cc
C:\Users\heller.HELLERIM\.node-gyp\0.10.29\deps\v8\include\v8.h(184): warning C4506: no definition for inline function 'v8::Persistent<v8::Object> v8::Persistent<v8::Object>::New(v8::Handle<v8::Object>)' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv\build\iconv.vcxproj]
LINK : fatal error LNK1104: cannot open file 'libcpmt.lib' [C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv\build\iconv.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\heller.HELLERIM\AppData\Roaming\npm\node_modules\node-expat\node_modules\iconv
gyp ERR! node -v v0.10.29
 v0.13.1 \node-gyp -v
gyp ERR! not ok
npm ERR! iconv@2.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iconv@2.1.6 install script.
npm ERR! This is most likely a problem with the iconv package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls iconv
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "node-expat" "--msvs_version=2013"
npm ERR! cwd C:\Users\heller.HELLERIM
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\heller.HELLERIM\npm-debug.log
npm ERR! not ok code 0

**Comment by lloydwatkin** [comment]
Then I'm afraid the iconv project is your next place to raise an issue. If you could link back here that would be greatly appreciated.

**Comment by hellerim** [comment]
Thank you!
 
Kind regards
 
Goetz Heller
 
Von: Lloyd Watkin [mailto:notifications@github.com] 
Gesendet: Donnerstag, 19. März 2015 18:25
An: node-xmpp/node-expat
Cc: hellerim
Betreff: Re: [node-expat] cannot install on Windows 8.1 64bit with MSVS version 2013 (#113)
 
Then I'm afraid the iconv project is your next place to raise an issue. If you could link back here that would be greatly appreciated.

**Comment by hellerim** [comment]
Meanwhile, I replaced the VS 2013 Express installation with VS 2013 Community Edition which ships with libcpmt.lib that could not be found until then. Now the buid runs through with a couple of warnings, But these appear to not be significant for 64-bit environments.

Anyway, thank you verymuchfor your help.
