### ISSUE TITLE
Install node office

### ISSUE THREAD

**Issue by macgera** [node-xmpp/node-expat#122]
Try install office. https://www.npmjs.com/package/office

`npm install officee`

But i got error with node-expat and node-gyp :/ 

<pre>
npm install office
-
> node-expat@2.0.0 install /Users/michael/workspace/Archer-software/test/awm-docapi/server/node_modules/office/node_modules/xml2json/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
../deps/libexpat/lib/xmltok.c:471:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:484:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:504:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:517:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:730:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:749:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:762:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:775:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:871:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
../deps/libexpat/lib/xmltok.c:890:1: warning: missing field 'isName2'
      initializer [-Wmissing-field-initializers]
};
^
10 warnings generated.
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
../node-expat.cc:54:34: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> New(const Arguments& args)
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:99:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Parse(const Arguments& args)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:171:42: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> SetEncoding(const Arguments& args)
                                         ^~~~~~~~~
                                         v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:198:39: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetError(const Arguments& args)
                                      ^~~~~~~~~
                                      v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:212:35: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Stop(const Arguments& args)
                                  ^~~~~~~~~
                                  v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:229:37: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Resume(const Arguments& args)
                                    ^~~~~~~~~
                                    v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:244:36: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> Reset(const Arguments& args)
                                   ^~~~~~~~~
                                   v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:272:51: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetCurrentLineNumber(const Arguments& args)
                                                  ^~~~~~~~~
                                                  v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:285:53: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetCurrentColumnNumber(const Arguments& args)
                                                    ^~~~~~~~~
                                                    v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:298:50: error: unknown type name 'Arguments'; did you mean
      'v8::internal::Arguments'?
  static Handle<Value> GetCurrentByteIndex(const Arguments& args)
                                                 ^~~~~~~~~
                                                 v8::internal::Arguments
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../node-expat.cc:22:17: error: calling a protected constructor of class
      'v8::HandleScope'
    HandleScope scope;
                ^
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../node-expat.cc:23:55: error: cannot initialize a parameter of type
      'v8::Isolate *' with an lvalue of type 'Handle<v8::Value> (const
      v8::internal::Arguments &)'
    Local<FunctionTemplate> t = FunctionTemplate::New(New);
                                                      ^~~
/Users/michael/.node-gyp/0.12.7/deps/v8/include/v8.h:3456:16: note: passing
      argument to parameter 'isolate' here
      Isolate* isolate,
               ^
../node-expat.cc:27:43: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "parse", Parse);
                                          ^~~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:28:49: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "setEncoding", SetEncoding);
                                                ^~~~~~~~~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:29:46: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "getError", GetError);
                                             ^~~~~~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:30:42: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "stop", Stop);
                                         ^~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:31:44: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "resume", Resume);
                                           ^~~~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:32:43: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "reset", Reset);
                                          ^~~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
../node-expat.cc:33:58: error: cannot initialize a parameter of type
      'v8::FunctionCallback' (aka 'void (*)(const
      FunctionCallbackInfo<v8::Value> &)') with an lvalue of type
      'Handle<v8::Value> (const v8::internal::Arguments &)': type mismatch at
      1st parameter ('const FunctionCallbackInfo<v8::Value> &' vs 'const
      v8::internal::Arguments &')
    NODE_SET_PROTOTYPE_METHOD(t, "getCurrentLineNumber", GetCurrentLineNumber);
                                                         ^~~~~~~~~~~~~~~~~~~~
/Users/michael/.node-gyp/0.12.7/src/node.h:246:60: note: passing argument to
      parameter 'callback' here
                                      v8::FunctionCallback callback) {
                                                           ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/node_expat/node-expat.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/michael/workspace/Archer-software/test/awm-docapi/server/node_modules/office/node_modules/xml2json/node_modules/node-expat
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "office"
npm ERR! node v0.12.7
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michael/workspace/Archer-software/test/awm-docapi/server/npm-debug.log
</pre>

I read all issues, try do lot of things, remove ~/.npm, ~/.node-gyp. Reinstall node-gyp, and lot things from github issues, stackoveflow & google. 

I don't understand the problem :/
My configuration Mac OS 10.10.5. Also on Ubuntu 14 same problem.

**Comment by lloydwatkin** [comment]
Can you try installing the latest version please?

**Comment by macgera** [comment]
I try. Cloned office package and run npm install manualy for each package.

**Comment by macgera** [comment]
Solve this via http://stackoverflow.com/questions/17628416/node-js-install-canvas-failed-on-mac-osx-10-8-4-src-canvas-h-fatal-error
