### ISSUE TITLE
Fail to install on windows 8 x64

### ISSUE THREAD

**Issue by fredericosilva** [node-xmpp/node-expat#50]
Hello, 

I've no experience with node-gyp, any idea where to look for the error?

$ node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@0.7.1
gyp info using node@0.8.11 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'c:\\Users\\frederico.silva\\.node-gyp\\0.8.11\\tools\\gyp\\gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2010',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\frederico.silva\\Documents\\GitHub\\node-expat\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Users\\frederico.silva\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Users\\frederico.silva\\.node-gyp\\0.8.11\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=c:\\Users\\frederico.silva\\.node-gyp\\0.8.11',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\frederico.silva\\Documents\\GitHub\\node-expat',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\frederico.silva\\Documents\\GitHub\\node-expat\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/property:TargetExt=.node',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.Cpp.InvalidPlatform.Targets(23,7): error MSB8007: The Platform for project 'expat.vcxproj' is invalid.  Platform='x64'. You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Platform that doesn't exist for this project. [C:\Users\frederico.silva\Documents\GitHub\node-expat\build\deps\libexpat\expat.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Users\frederico.silva\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:236:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:96:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Users\\frederico.silva\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\frederico.silva\Documents\GitHub\node-expat
gyp ERR! node -v v0.8.11
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok 

Thank you.

**Comment by Fnck** [comment]
just installed the m$ c++ compiler package and the issue is resolved, thank u all!
