### ISSUE TITLE
bench.js: performance measuring under Windows is off

### ISSUE THREAD

**Issue by sp00x** [node-xmpp/node-expat#73]
Not a 'bug' but:

Apparently setTimeout(d,0) on Windows gives very poor performance - I was getting "65 el/s" on all the different parsers. Replacing the call with setImmediate(d) gives much higher values, and probably more accurate ones :)

(Gave me: expat: 98K, sax: 29K, libxmsjs: 79K, node-xml: 36K. Node v0.10.12)

**Comment by sonnyp** [comment]
benchmark now uses http://benchmarkjs.com/
