### ISSUE TITLE
Installation failed on Windows 7 64-bit

### ISSUE THREAD

**Issue by timcullen** [node-xmpp/node-expat#94]
Am trying to NPM install node-expat onto a windows 7 64 bit machine.  node-gyp installs fine on a standalone basis with no errors.  However, node-expat throws a number of warnings: e.g. warning C4244: 'return' conversion from __int64 to XML_Index,
followed by a LINK fatal error LNK1181 cannot open input file kernel32.lib [c:.........\node-modules\node-expat\build\node-expat.vcxproj]

I'm developing a node/angularJS app and a bit out of my depth with the windows visual studio stuff.  Can anyone identify what I'm doing wrong please?

Extracts from npm-debug.txt below

369 info linkStuff node-expat@2.3.0
370 verbose linkBins node-expat@2.3.0
371 verbose linkMans node-expat@2.3.0
372 verbose rebuildBundles node-expat@2.3.0
373 info install node-expat@2.3.0
374 verbose unsafe-perm in lifecycle true
375 info node-expat@2.3.0 Failed to exec install script
376 info C:\Users\Tim Cullen\Documents\Mojo-Angular\node_modules\node-expat unbuild
377 info preuninstall node-expat@2.3.0
378 info uninstall node-expat@2.3.0
379 verbose true,C:\Users\Tim Cullen\Documents\Mojo-Angular\node_modules,C:\Users\Tim Cullen\Documents\Mojo-Angular\node_modules unbuild node-expat@2.3.0
380 info postuninstall node-expat@2.3.0
381 error node-expat@2.3.0 install: `node-gyp rebuild`
381 error Exit status 1
382 error Failed at the node-expat@2.3.0 install script.
382 error This is most likely a problem with the node-expat package,
382 error not with npm itself.
382 error Tell the author that this fails on your system:
382 error     node-gyp rebuild
382 error You can get their info via:
382 error     npm owner ls node-expat
382 error There is likely additional logging output above.
383 error System Windows_NT 6.1.7601
384 error command "C:\\Users\\Tim Cullen\\Documents\\nodejs\\\\node.exe" "C:\\Users\\Tim Cullen\\Documents\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-expat"
385 error cwd C:\Users\Tim Cullen\Documents\Mojo-Angular
386 error node -v v0.10.25
387 error npm -v 1.3.24
388 error code ELIFECYCLE
389 verbose exit [ 1, true ]

**Comment by rochal** [comment]
+1 getting same issue on Windows 7 with VS 2013.

Unfortunately node-expat is the flakiest module we have ever dealt with...

**Comment by lloydwatkin** [comment]
If someone with access to a windows system is willing to put in a pull request to fix this issue I am more than happy to accept, but as I don't have access to a windows system this is very hard for me to work on/fix this.

**Comment by Pomax** [comment]
is node-xmpp backed by any company? Getting a single license key for windows 7 pro is less than $150, especially now that it's mostly legacy disks, it's a pretty sensible investment for any developer intending to target multiple platforms (OSX machine, and parallels running a win7 bootcamp partition and linux VM for proper cross-platform testing. Given the price of the mac, the last bits are pretty much insignificant cost for massive developer return =)

**Comment by lloydwatkin** [comment]
`node-xmpp` is not backed by any company. Ideally it would be best to get someone familiar (and invested) in the windows version working. We are open to windows developers volunteering their time.
